# Generated by Django 4.2.5 on 2023-09-13 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("eventapp", "0004_application_delete_form"),
    ]

    operations = [
        migrations.CreateModel(
            name="Applicant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=120)),
                ("email", models.CharField(max_length=120)),
                ("phone", models.CharField(max_length=120)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="eventapp.event"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Application",
        ),
    ]
